/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pim.facade;

import br.com.pim.model.BaseEntity;
import java.io.Serializable;
import java.util.List;


public class EntityFacade extends AbstractFacade {

    public <E extends BaseEntity> E find(Class<E> clazz, Serializable id) {
        return getGenericDao().find(clazz, id);
    }

    public <E extends BaseEntity> void persist(E obj) {
        getGenericDao().persist(obj);

        // force the flush of the cache to make sure that the persist
        // worked and return the ID generated by the database.
        getGenericDao().flushEm();
    }

    public <E extends BaseEntity> E merge(E obj) {
        return getGenericDao().merge(obj);
    }

    public <E extends BaseEntity> void remove(E obj) {
        // Merge the entity first to prevent the system fail on the remove
        E toRemove = getGenericDao().merge(obj);

        // actually remove the entity
        getGenericDao().remove(toRemove);
    }

    public <E extends BaseEntity> void remove(List<E> list) {
        for (E obj : list) {
            remove(obj);
        }
    }

    public <E extends BaseEntity> void merge(List<E> list) {
        for (E obj : list) {
            merge(obj);
        }
    }

}
